### ISSUE TITLE
None metrics in Graphite publisher - none "intel/logs/*"

### ISSUE THREAD

**Issue by varmax1** [intelsdi-x/snap-plugin-collector-logs#15]
Dears!
Pls take a look on this issue - 
it would be great if you may suggest some solution.
All components runs on one Ubuntu virtual.

Thanks very much,

Best regards,
Richard

**Snap daemon version** (use `snapteld -v`):
snapteld version 1.3.0

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- **Kernel** (e.g. `uname -a`):
Linux ubuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Relevant tools** (e.g. plugins used with Snap):
snaptel version 1.3.0

**What happened**:
Write correctly to the MySQL and PostgreSQL, however in working Graphite
is no metrics shown.

**What you expected to happen**:
In Graphite is shown metric "intel/logs"

**Steps to reproduce it** (as minimally and precisely as possible):
{
  "version": 1,
  "schedule": {
    "type": "simple",
    "interval": "3s"
  },
  "workflow": {
    "collect": {
      "metrics": {
        "/intel/logs/*": {}
      },
      "config": {
        "/intel/logs": {
          "metric_name": "nova_logs",
          "cache_dir": "/home/test/cache/snap",
          "log_dir": "/home/test/logs/(nova|neutron)",
          "log_file": ".*",
          "splitter_type": "date-time",
          "splitter_pos": "before",
          "collection_time": "2s",
          "metrics_limit": 1000
        }
      },
      "publish": [
        {
          "plugin_name": "graphite",
          "config": {
            "server": "10.42.15.211",
            "port": 2003
          }
        },
        {
          "plugin_name": "postgresql",
          "config": {
            "hostname": "10.42.15.211",
            "port": 5432,
            "username": "snap",
            "password": "snap",
            "database": "snap",
            "table_name": "log_010x042x015x211"
          }
        },
        {
          "plugin_name": "mysql",
          "config": {
            "username": "snap",
            "password": "snap",
            "hostname": "10.42.15.211",
            "port": "3306",
            "database": "snap",
            "tablename": "log_010x042x015x211"
          }
        }
      ]
    }
  }
}
**Anything else do we need to know** (e.g. issue happens only occasionally):
sudo docker run --name PostgreSQLServer --restart=always -p 5432:5432 -e POSTGRES_PASSWORD=snap -e POSTGRES_USER=snap -e POSTGRES_DB=snap -d postgres
sudo docker run --name MySQLServer --restart=always -p 3306:3306 -e MYSQL_ROOT_PASSWORD=snap -e MYSQL_USER=snap -e MYSQL_PASSWORD=snap -e MYSQL_DATABASE=snap -d mysql/mysql-server
sudo docker run -d --name graphite --restart=always -p 80:80 -p 2003-2004:2003-2004 -p 2023-2024:2023-2024 -p 8125:8125/udp -p 8126:8126 hopsoft/graphite-statsd
sudo docker run -d -v /var/lib/grafana --name grafana-storage --restart=always busybox:latest
sudo docker run -d -p 3000:3000 --name=grafana --restart=always  --volumes-from grafana-storage grafana/grafana

**Comment by Armatorix** [comment]
Hi @varmax1 !
Graphite is good publisher plugin, but for numeric metrics that can be placed on graph. As far as I know graphite is not picking string data. Are you sure you want exactly graphite publisher to collect logs?

**Comment by varmax1** [comment]
Opps ... understand.

Thanks Wojciech!

2017-08-09 9:25 GMT+02:00 Wojciech Sokołowski <notifications@github.com>:
